# DP-1 = Dell G2724D / main landscape
# Workspaces 1-7 default to horizontal scroller
tagrule=id:1,monitor_name:DP-1,layout_name:scroller
tagrule=id:2,monitor_name:DP-1,layout_name:scroller
tagrule=id:3,monitor_name:DP-1,layout_name:scroller
tagrule=id:4,monitor_name:DP-1,layout_name:scroller
tagrule=id:5,monitor_name:DP-1,layout_name:scroller
tagrule=id:6,monitor_name:DP-1,layout_name:scroller
tagrule=id:7,monitor_name:DP-1,layout_name:scroller

# DP-2 = Lenovo P27q-20 / vertical
# Workspaces 8-9 default to vertical scroller
tagrule=id:8,monitor_name:DP-2,layout_name:vertical_scroller
tagrule=id:9,monitor_name:DP-2,layout_name:vertical_scroller
